### ISSUE TITLE
Option for new line and indentation

### ISSUE THREAD

**Issue by stevenyix** [lvsecoto/to_string#1]
Thank you for creating this - great time saver.  Would you consider adding a feature that allows for 'pretty printing' the output of the ToString() method?  

Sometimes it's easier to view the output in multiple lines with indentation.  Example:

classname {
   (tab/indent) property1: xxx
   (tab/indent) property2: yyy
   (tab/indent) property3: zzz
}

**Comment by lvsecoto** [comment]
Yes, that's a great idea.

Now to_string 1.2.0 supports pretty print!

Try this:
Use `ToString()` annotation:

```dart
ToString(
    prettyPrint: true,

    // default to "  "
    indent: "  ",
)
/// class Cat {...
```

Or create a file `build.yaml` with code and enable all class pretty print:
```yaml
targets:
  $default:
    builders:
      to_string_generator|to_string:
        options:
          prettyPrint: true
          indent: "  "
```

Then `toString()` pretty print like this:

```
Cat{
  classify: Animal,
  color: red,
  weight: 12.0,
  wings: has,
  ball: Ball{         <= nested
    color: red,
  },
}
```
